### ISSUE TITLE
Implement commodity utilizations in balanceResidual

### ISSUE THREAD

**Issue by joshbrowning2358** [SWS-Methodology/faoswsStandardization#8] opened 2016-03-25 08:41 UTC
The balanceResidual function balances each of the SUA commodities by allocating the imbalance to either production (in the case of over-utilization) or to a single utilization element (in the case of over-supply).  This allocation should go to the most reasonable utilization of that commodity: for example, flour should be allocated to food, bran should be allocated to feed, and starch should be allocated to industrial utilization.  The function can perform this allocation, but we need the data.

**Comment by sebastian-c** [comment] 2016-06-20 16:24
Duplicate of #1

**Closed as completed by sebastian-c** 2016-06-20 16:24 UTC
Labels: bug, duplicate, table-missing
